### ISSUE TITLE
It does not work at all

### ISSUE THREAD

**Issue by InfernuZGD** [geode-sdk/textureldr#18]
https://github.com/geode-sdk/textureldr/assets/117394386/f90ad4f0-4880-40b1-b762-7f5e058c5ecb

**Comment by RayDeeUx** [comment]
disable megahack and try again

**Comment by GitGuy64** [comment]
i have same issue and i do not use megahack

**Comment by GitGuy64** [comment]
i applied

**Comment by GitGuy64** [comment]
and no work

**Comment by GitGuy64** [comment]
turn off megahack or in the loader menu, move the pack to applied and click apply
