### ISSUE TITLE
Manipulate geode textures/sprites/icons

### ISSUE THREAD

**Issue by JoJoBollo** [geode-sdk/textureldr#20]
This more than an issue is a question, as maybe this wasn't intended.

I'm trying to add to my tp custom icons for the geode buttons on the menu screen, but I don't really know how to set the directories to actually detect it and put it. When I paste everything on the real directories of geode resources it works succesfully, so I wanted to know if there's a way to boot up with the geode tp with the tp loader, if that makes sense

**Comment by TheSillyDoggo** [comment]
create a folder in your pack folder called the mod is, so for geode it's "geode.loader"

**Comment by TheSillyDoggo** [comment]
Then put your replaced files in the folder

**Comment by matcool** [comment]
the example pack mentioned in the readme literally does this
