### ISSUE TITLE
Mod completely breaks textures of geode loader

### ISSUE THREAD

**Issue by TheNormalestPeep** [geode-sdk/textureldr#26]
![image](https://github.com/geode-sdk/textureldr/assets/75856557/065cc80b-e5e3-4441-98b8-6bf18bf46f1d)

**Comment by matcool** [comment]
No, this is a bug with geode itself

**Comment by TheNormalestPeep** [comment]
This only occurs after enabling texture loader though

**Comment by matcool** [comment]
then you have a texture pack which changes geode's textures, which changed quite a lot in 3.0
