### ISSUE TITLE
Me dumb me don't understand why it isn't working

### ISSUE THREAD

**Issue by YarikZhiga** [geode-sdk/textureldr#32]
Ok so I downloaded this texture pack from gamejolt
https://gamejolt.com/games/DeltaruneGD/664470

And when I try to apply it, it only replaces some buttons with missing textures but successfully changes the music? Can someone please help? Maybe the file structure is wrong or something?
![Screenshot_2024-07-01-05-47-32-323_com geode launcher](https://github.com/geode-sdk/textureldr/assets/97826544/db8da47b-1249-4f0f-98a6-4f5c18c28ba7)

Sorry if this is not the right place to ask 🙏

**Comment by Kingminer7** [comment]
It looks like that pack was made for 2.11

**Comment by YarikZhiga** [comment]
> It looks like that pack was made for 2.11
> 
> Edit: Yeah that pack isn't updated for 2.206

Weird, I'm pretty sure I saw it in Daily Dose of GD a few days ago :(
