### ISSUE TITLE
Formatting question

### ISSUE THREAD

**Issue by woodgoldtwo** [geode-sdk/textureldr#35]
how are you supposed to format the packs exactly? the readme linked on the modpage doesn't specify it

are the textures supposed to be placed in packname.zip/resources/ or packname.zip/ or somewhere else??

is the pack.json mandatory?

can you even edit vanilla textures??

the readme really isn't that useful

**Comment by Woodgoldtwo** [comment]
sorry if that came off as a bit harsh, things like this just really frustrate me

**Comment by Alphalaneous** [comment]
While either way works, the read me does say: “Make sure to put the files are the root of the zip! otherwise Texture Loader might not find them properly.”

**Comment by Alphalaneous** [comment]
Pack.json isn’t mandatory, but is good if you want extra pack metadata to be shown

**Comment by woodgoldtwo** [comment]
the reason I asked is because I did put the textures directly in packname.zip and it didn't work

**Comment by matcool** [comment]
The example pack edits both mod textures and vanilla textures. the vanilla texture edited is `GJ_gradientBG-hd.png` and it is placed at the **root of the zip**, with the **exact** same file name as the texture its replacing.

**Comment by woodgoldtwo** [comment]
oh ok thanks

**Comment by woodgoldtwo** [comment]
> The example pack edits both mod textures and vanilla textures. the vanilla texture edited is `GJ_gradientBG-hd.png` and it is placed at the **root of the zip**, with the **exact** same file name as the texture its replacing.

where and/or what is the root of the zip, it's that part that I don't understand

**Comment by HenrySck075** [comment]
> where and/or what is the root of the zip, it's that part that I don't understand

the root of the zip is the very directory shown when you open the zip file 👍

**Comment by woodgoldtwo** [comment]
> > where and/or what is the root of the zip, it's that part that I don't understand
> 
> the root of the zip is the very directory shown when you open the zip file 👍

I've already tried putting the textures there but it didn't work

**Comment by woodgoldtwo** [comment]
[pack.zip](https://github.com/user-attachments/files/16336749/pack.zip)
here's the pack I'm trying to use, maybe this helps?

**Comment by HenrySck075** [comment]
can you try moving those to a folder named icons instead
i have to sleep

**Comment by woodgoldtwo** [comment]
> can you try moving those to a folder named icons instead i have to sleep

that worked thank you!!
