### ISSUE TITLE
Texture pack does not apply even with correct one

### ISSUE THREAD

**Issue by JerichoGesolgani** [geode-sdk/textureldr#36]
For context if i appiled for e.g. ufo 18 with modified ufo 18 even on correct graphic setting medium/hd for example its still does not appiled instead remains unchanged please fix it and i have tested this in other android phone and still the issue persist only that chnage is the trail/streak file and mp3 file

**Comment by matcool** [comment]
icons must be in the icons folder.

**Comment by JerichoGesolgani** [comment]
That what i did but this not completed yet for example when put modified ufo 18 hd in my texture pack folder still not work
