### ISSUE TITLE
Wraith texture is missing

### ISSUE THREAD

**Issue by DemiSans** [geode-sdk/textureldr#43]
![image](https://github.com/user-attachments/assets/70f88081-60f4-4b62-9a7f-0d596548fecc)

every other mod is disabled

**Comment by Alphalaneous** [comment]
This is due to your texture pack not having it

**Comment by DemiSans** [comment]
@Alphalaneous huh, so disabling Texture Workshop didnt switch back all textures to vanilla one... Interesting

**Comment by hiimjustin000** [comment]
@DemiSans You have to unload textures in Texture **Loader**, not Texture Workshop.
![image](https://github.com/user-attachments/assets/333a6224-67e4-4014-8fc5-4b54b0a035ca)

**Comment by DemiSans** [comment]
Yeah, I already figured that out, thx
