### ISSUE TITLE
Missing vault icon and gold key texture

### ISSUE THREAD

**Issue by CyberCat30** [geode-sdk/textureldr#49]
![20241206125328_1](https://github.com/user-attachments/assets/25a011b4-6825-4404-940b-67c692e5c3a9)
![20241206125337_1](https://github.com/user-attachments/assets/95f9a280-4b8b-483c-acd3-8330441d28f4)

**Comment by hiimjustin000** [comment]
@CyberCat30 Your texture pack doesn't have those textures, as your texture pack was made for an older version.
