### ISSUE TITLE
Please, add tutorial for this mod.

### ISSUE THREAD

**Issue by DXGOfficial** [geode-sdk/textureldr#5]
I just spent 1 hour on thinking, how this sh1t works on Android, and i'm even never loaded any texture pack, because it's redirecting to that intended Google's bs files app, in which, i can't even load the TP folder. I'm think, it's better to include a tutorial, even it's have to be useful only for mobile users.
Thanks for helping.

**Comment by TheSillyDoggo** [comment]
Google files is a new android issue

**Comment by DXGOfficial** [comment]
Also, if you don't know, what the hell is that "Google's intended files app", well this is that file manager with blue icon, which is appearing, when you droping files to something, like browser or files-related app.
![ap_resize](https://github.com/geode-sdk/textureldr/assets/157183465/9936bb92-9a72-489a-ad59-5251350aca46)

**Comment by 3squ** [comment]
All you have to do is paste your textures in the following directory:

/Android/media/com.geode.launcher/game/geode/config/geode.texture-loader/packs

Remember that 2.1 tps, and uhd textures are not supported.

**Comment by TheSillyDoggo** [comment]
Also just to add, on newer android versions (12+ I think) you can't actually access that folder on the phone you need to plug it into a PC which is very stupid

**Comment by 3squ** [comment]
I blame Google for creating such Inconvenience

**Comment by TheSillyDoggo** [comment]
Who else could we blame? We're not even real.

**Comment by DXGOfficial** [comment]
Thanks for helping me.
